config/routes.rb
Rails.application.routes.draw do

  get 'prices/load/:ticker' => 'prices#load'
  get 'prices/:ticker' => 'stocks#price'

  resources :prices

  resources :stocks

  resources :annotations

  devise_for :users

  root 'welcome#index'

end

app/models/annotation.rb
class Annotation < ActiveRecord::Base
  belongs_to :user
end

app/models/price.rb
class Price < ActiveRecord::Base
end

app/models/stock.rb
class Stock < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :prices
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :annotations
  has_and_belongs_to_many :stocks
end

app/controllers/annotations_controller.rb
class AnnotationsController < ApplicationController
  before_action :set_annotation, only: [:show, :edit, :update, :destroy]

  def index
    # Phrase it this way to allow for logged-out users
    if params[:order] == 'asc'
      @annotations = Annotation.where(user: current_user).order(date: :asc)
    else
      @annotations = Annotation.where(user: current_user).order(date: :desc)
    end
    respond_with(@annotations)
  end

  def show
    respond_with(@annotation)
  end

  def new
    @annotation = Annotation.new
    respond_with(@annotation)
  end

  def edit
  end

  def create
    @annotation = Annotation.new(annotation_params)
    @annotation.user = current_user
    @annotation.save
    respond_with(@annotation)
  end

  def update
    @annotation.update(annotation_params)
    respond_with(@annotation)
  end

  def destroy
    @annotation.destroy
    respond_with(@annotation)
  end

  private
    def set_annotation
      @annotation = Annotation.find(params[:id])
    end

    def annotation_params
      params.require(:annotation).permit(:title, :date, :content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # XXX: Disable CSRF protection for now to simplify the code.
  # protect_from_forgery with: :null_session

  respond_to :html, :json
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  before_action :set_price, only: [:show, :edit, :update, :destroy]

  def index
    @prices = Price.all
    respond_with(@prices)
  end

  def show
    respond_with(@price)
  end

  def new
    @price = Price.new
    respond_with(@price)
  end

  def edit
  end

  def create
    @price = Price.new(price_params)
    @price.save
    respond_with(@price)
  end

  def update
    @price.update(price_params)
    respond_with(@price)
  end

  def destroy
    @price.destroy
    respond_with(@price)
  end

  def load
    @stocks = Stock.where(ticker:params[:ticker])
    @stocks.each do |i|
      data = YahooFinance.historical_quotes(i.ticker, Time::now-(24*60*60*3650), Time::now, { raw: false, period: :daily })
      data.each do |j|
        Price.create(close_date:j.trade_date, close_price:j.close, stock_id:i.id)
      end
    end
  end


  private
    def set_price
      @price = Price.find(params[:id])
    end

    def price_params
      params.require(:price).permit(:close_date, :close_price)
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]

  def price
    # Only showing one
    @displayStock = Stock.where(ticker:params[:ticker])
    @stockid = @displayStock.first.id
    @prices = Price.where(stock_id: @stockid).order(close_date: :asc)

    @price_array = []

    @prices.each do |p|
      @price_array.push [p.close_date.to_time.to_i * 1000, p.close_price]
    end

    @price_array
  end


  def index
    #In many to many relationships, need to do current_user.stocks rather than Stock.user because one stock has many users.
    @stocks = current_user.stocks
    respond_with(@stocks)
  end

  def show
    respond_with(@stock)
  end

  def new
    @stock = Stock.new
    respond_with(@stock)
  end

  def edit
  end

  def create
    @stock = Stock.new(stock_params)
    @stock.save
    #Save the new data entry into current user's portfolio (ie current_user.stocks)
    current_user.stocks << @stock
    respond_with(@stock)
  end

  def update
    @stock.update(stock_params)
    respond_with(@stock)
  end

  def destroy
    @stock.destroy
    respond_with(@stock)
  end

  private
    def set_stock
      @stock = Stock.find(params[:id])
    end

    def stock_params
      params.require(:stock).permit(:ticker)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/annotations_helper.rb
module AnnotationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/annotations/_form.html.erb
<%= form_for(@annotation) do |f| %>
  <% if @annotation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@annotation.errors.count, "error") %> prohibited this annotation from being saved:</h2>

      <ul>
      <% @annotation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/annotations/edit.html.erb
<h1>Editing annotation</h1>

<%= render 'form' %>

<%= link_to 'Show', @annotation %> |
<%= link_to 'Back', annotations_path %>

app/views/annotations/index.html.erb
<h1>Listing annotations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @annotations.each do |annotation| %>
      <tr>
        <td><%= annotation.title %></td>
        <td><%= annotation.date %></td>
        <td><%= annotation.content %></td>
        <td><%= link_to 'Show', annotation %></td>
        <td><%= link_to 'Edit', edit_annotation_path(annotation) %></td>
        <td><%= link_to 'Destroy', annotation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Annotation', new_annotation_path %>

app/views/annotations/new.html.erb
<h1>New annotation</h1>

<%= render 'form' %>

<%= link_to 'Back', annotations_path %>

app/views/annotations/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @annotation.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @annotation.date %>
</p>

<p>
  <strong>Content:</strong>
  <%= @annotation.content %>
</p>

<%= link_to 'Edit', edit_annotation_path(@annotation) %> |
<%= link_to 'Back', annotations_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>$tockAnnotator</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body ng-app="myAnnotation">

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/"><i class="fa fa-usd fa-spin"></i> tockAnnotator</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="#about">About</a></li>
        <li><a href="#contact">Contact</a></li>
      </ul>
      <p class="navbar-text pull-right">

    <!--
    Devise Signup/Login. Still needs to modal functionality. Curently sends user to another page
    =========================================================================================-->
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
        <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>

    </div><!--/.nav-collapse -->
  </div>
</nav>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

<%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js' %>
  <%= javascript_include_tag '//code.highcharts.com/stock/highstock.js' %>
  <%= javascript_include_tag '//code.highcharts.com/stock/modules/exporting.js' %>
</body>
</html>

app/views/prices/_form.html.erb
<%= form_for(@price) do |f| %>
  <% if @price.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@price.errors.count, "error") %> prohibited this price from being saved:</h2>

      <ul>
      <% @price.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :close_date %><br>
    <%= f.date_select :close_date %>
  </div>
  <div class="field">
    <%= f.label :close_price %><br>
    <%= f.text_field :close_price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<h1>Listing prices</h1>

<table>
  <thead>
    <tr>
      <th>Close date</th>
      <th>Close price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prices.each do |price| %>
      <tr>
        <td><%= price.close_date %></td>
        <td><%= price.close_price %></td>
        <td><%= link_to 'Show', price %></td>
        <td><%= link_to 'Edit', edit_price_path(price) %></td>
        <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Price', new_price_path %>

app/views/prices/load.html.erb
<div>Hello</div>

app/views/prices/new.html.erb
<h1>New price</h1>

<%= render 'form' %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Close date:</strong>
  <%= @price.close_date %>
</p>

<p>
  <strong>Close price:</strong>
  <%= @price.close_price %>
</p>

<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>

app/views/stocks/_form.html.erb
<%= form_for(@stock) do |f| %>
  <% if @stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% @stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticker %><br>
    <%= f.text_field :ticker %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing stock</h1>

<%= render 'form' %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<h1>Listing stocks</h1>

<table>
  <thead>
    <tr>
      <th>Ticker</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
      <tr>
        <td><%= stock.ticker %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New stock</h1>

<%= render 'form' %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticker:</strong>
  <%= @stock.ticker %>
</p>

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>

app/views/welcome/index.html.erb
<div class="row" ng-controller="StockController">
  <div class="col-md-9" id="logged-out-stock-chart" ng-hide="checked">
    ADD STOCKS<br> CLICK <strong>REFRESH CHART</strong>
  </div>
  <div class="col-md-9 stock-chart" ng-show="checked">
    <div id="container" style="height: 400px; min-width: 310px"></div>
  </div>
  <br>
  <div class="col-md-3 stock-ticker">
    <div class="input_board">
      <form class="insert-ticker" ng-submit="submitStock(); saveData()">
        <input type="text" ng-model="stock" placeholder="Ticker symbol">
        <input name="commit" type="submit" value="Add Stock">
      </form>
    </div>
    <div id="tickerLoadingMsg" ng-hide="hideLoadingButton"><img src="assets/ajax-loader.gif" alt="loading"></div>

    <div ng-repeat="object in stored_stocks">
      <div class="stock_item">
        <div>
          <input type="checkbox" ng-model="object.checked">
          {{object.ticker}}
          <span class="glyphicon glyphicon-remove" aria-hidden="true" ng-click="deleteStock(object.id)"></span>
        </div>
      </div>
    </div>

    <button type="button" class="btn btn-default" ng-click="refreshChart()">Refresh Chart</button>

  </div>
</div>
<hr>
<!-- My Annotations -->
<div class="row below" ng-controller="AnnotationController">
  <div class="col-md-5 annotation">

<!-- True inout board -->
    <div class="input_board user-annotations">
      <form>
        <br>
        <input type="text" ng-model="title" placeholder="Title...">
        <br><br>
        <input type="date" ng-model="annodate">
        <br><br>
        <textarea ng-model="annotation" name="annotation[content]" rows="13" cols="70" placeholder="Write your note here..."></textarea>
        <br>
        <input name="commit" type="submit" value="Add Note" ng-click="submitAnnotation()">

      </form>
    </div>
  </div>

<!-- Displays Data -->
  <div class="search">
  </div>
  <div class="col-md-7 show-annotation">
    <div class="search">
      <input type="search" ng-model="search" placeholder="Search..." size="50">
    </div>
    <hr>
    <div id="logged-out-show-annotation" ng-show="annotations_show">
      WRITE NOTE<br>CLICK <strong>ADD NOTE</strong>
    </div>
    <div class="annotation-row" ng-repeat="object in stored_annotations | filter:search" ng-hide="annotations_show">
      <div class="annotation_item" ng-hide="editing">
        <h3>{{object.title}}</h3>
        <div>{{object.date}}</div>
        <br>
        <div>{{object.content}}</div>
        <hr>
        <span class="glyphicon glyphicon-remove" aria-hidden="true" ng-click="deleteAnnotation(object.id)"></span>
        <span class="glyphicon glyphicon-edit" aria-hidden="true" ng-click="editing = true"></span>
      </div>
      <form ng-show="editing" ng-dblclick="editing = false; updateAnnotation(object)">
        <input type="text" ng-model="object.title" >
        <input type="text" ng-model="object.date">
        <textarea ng-model="object.content" name="annotation[content]" rows="8" cols="50" placeholder="Write your note here"></textarea>
      </form>
    </div>
  </div>
</div>